server:
  servlet:
    context-path: /migration

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:test}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:root}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:test_revalidation}?authSource=admin&authMechanism=SCRAM-SHA-1
  batch:
    job:
      enabled: false

datasource:
  tis:
    jdbc-url: jdbc:mysql://${TIS_DBHOST:localhost}:${TIS_DBPORT:3306}/${TIS_DBNAME:tcs}?useUnicode=${TIS_UNICODE:true}&characterEncoding=${TIS_ENCODING:utf8}&useSSL=${TIS_SSL:false}
    username: ${TIS_DBUSER:root}
    password: ${TIS_DBPASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
